PepperStones/FE

- package-lock.json
- package.json
- src/components/nav/FooterNav.tsx
- src/components/nav/TopNav.tsx
- src/constants/ServerURL.js
- src/pages/Login.tsx
> 💄Update: add top&footer nav

- src/components/InputField/LargeInput.tsx
- src/components/button/LargeBtn.tsx
- src/components/button/SmallBtn.tsx
- src/pages/Login.tsx
**Add btn color changing & PWD input effect**
> 🐛fix: btn color & PWD input effect #2

- src/App.tsx
- src/components/button/QuestRewardBtn.tsx
- src/pages/ChallengeQuest.tsx
- src/pages/Login.tsx
**Add challenge quest page & fix blur effect**
> ✨feat#4: add challenge quest page

- src/App.tsx
- src/components/nav/FooterNav.tsx
- src/components/nav/TopNav.tsx
- src/pages/Mypage.tsx
- src/styles/utilities.css
Update Add utilities css & fix color and font in Top&Footer nav
> 💄update: add utilities css

- src/pages/BoardPage.tsx
> ✨feat: 게시글 클릭 시 페이지 이동 구현 #17

- src/App.tsx
- src/components/modal/DefaultModal.tsx
- src/components/nav/FooterNav.tsx
- src/pages/admin/InsertMember.tsx
- src/pages/admin/MemberDetail.tsx
- src/pages/admin/Synchronization.tsx
Implement synchronization design #1
> ✨feat: impl synchronization design #1

- src/pages/CustomizingPage.tsx
- src/pages/Mypage.tsx
- src/pages/UpdatePwdPage.tsx
Add mypage animation #2
(fadeIn, move profile img and slide animation in tab bar)
> ✨feat: add mypage animation #2

- src/components/button/QuestCardBtn.tsx
- src/components/loading/ProgressCircle.tsx
- src/index.tsx
- src/pages/AllQuestPage.tsx
- src/pages/QuestDetailPage.tsx
- src/styles/utilities.css
Implement quest page design #2
> ✨feat: impl quest page design #2

- package-lock.json
- src/api/axiosInstance.ts
- src/api/user/notificationApi.ts
- src/api/user/registerFcmTokenAPI.ts
- src/pages/Login.tsx
- src/pages/NotificationList.tsx
- src/utils/firebase/messaging.ts
> ✨feat: impl push notification API 

- src/api/user/boardApi.ts
- src/pages/BoardDetail.tsx
- src/pages/BoardPage.tsx
> ✨feat:Integrated board API 

- src/pages/Splash.tsx
> 🐛fix: naviagte error in splash

- src/firebase-messaging-sw.template.js
- src/utils/firebase/messaging.ts
> fix: 객체명 변경

- src/App.tsx
- src/components/modal/PWAInstallModal.tsx
- src/constants/ServerURL.js
- src/constants/TokenExpireTime.js
- src/pages/Splash.tsx
- src/utils/ProtectedRoute.tsx
1. Prevent go back button
2. Fix login logic
> 🐛fix: prevent go back btn

- src/utils/ProtectedRoute.tsx
> 🐛fix: login direct error

- src/pages/CustomizingPage.tsx
- src/pages/Mypage.tsx
> 🐛fix: apply current skin

- src/pages/CustomizingPage.tsx
- src/pages/Mypage.tsx
🐛fix: apply current skin in customize page
> 🐛fix: apply current skin in customize page

- src/App.tsx
- src/components/modal/ForegroundPushModal.tsx
- src/index.tsx
- src/utils/firebase/messaging.ts
> 🐛fix: receive push message

- src/App.tsx
- src/firebase-messaging-sw.template.js
- src/utils/firebase/messaging.ts
🐛fix: debug fore%background push message
> 🐛fix: debug fore%background push message

- src/App.tsx
- src/pages/Login.tsx
- src/utils/firebase/messaging.ts
🐛fix: delete fore%background alert
> 🐛fix: delete fore%background alert

- src/App.tsx
- src/components/star/StarAnimation.tsx
[🐛fix: design change in toast](https://github.com/PepperStones/FE/commit/b72f3204ea6118534e0431e9489755e452d3fb0c)
> 🐛fix: design change in toast

- src/pages/Login.tsx
- src/utils/firebase/messaging.ts
🐛fix: remove alret & add loading
> 🐛fix: remove alret & add loading

- src/App.tsx
- src/utils/firebase/messaging.ts
> 🐛fix: foreground code fix

- src/utils/firebase/messaging.ts
> 🐛fix: foreground code fix 2

- src/components/button/QuestCardBtn.tsx
- src/components/loading/ProgressCircle.tsx
- src/pages/QuestDetailPage.tsx
🐛fix: change color of circle progress
> 🐛fix: change color of circle progress
